// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "./navbar";
import { Footer } from "./footer/footer";
import AgeGateWrapper from "./ageverify/AgeVerifyer"; // client component
import { Analytics } from "@vercel/analytics/next";
import Script from "next/script";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cricket Fantasy App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <Head>
        <link rel="icon" href="/logoicon.ico" />
      </Head> */}

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7558776021474229"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
        <AgeGateWrapper>
          <NavBar />
          {children}
          <Analytics />
          <Footer />
        </AgeGateWrapper>
      </body>
    </html>
  );
}
